version: "2"
services:
  node:
    image: node
    user: "node"
    working_dir: /home/node/app
    environment:
      - NPM_CONFIG_PREFIX=/home/node/.npm-global
    volumes:
      - ../../:/home/node/app
    container_name: node-beechat
    expose:
      - "4000"
    ports:
      - 4000:4000
    networks:
      - beechat-network
    command: bash -c "npm install && node server.js"
  mongodb1:
    image: mongo
    volumes:
      - ./mongo/db1:/data/db
      - ./mongo/script:/data
    container_name: mongodb1
    expose:
      - "27017"
    ports:
      - 27017:27017
    networks:
      - beechat-network
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs" ]
  mongodb2:
    image: mongo
    volumes:
       - ./mongo/db2:/data/db
    container_name: mongodb2
    networks:
      - beechat-network
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs" ]
  mongodb3:
    image: mongo
    volumes:
       - ./mongo/db3:/data/db
    container_name: mongodb3
    networks:
      - beechat-network
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs" ]
networks:
  beechat-network:
    driver: bridge